#!/bin/sh

launch_pipewire() {
        $SNAP/usr/bin/pipewire
        killall wireplumber || true
}

launch_wireplumber() {
        $SNAP/usr/bin/wireplumber
        killall pipewire || true
}

launch_pipewire &
launch_wireplumber
