#!/bin/bash

# Wait in background to link pipewire socket to location where other
# snaps will look for it.

mkdir -p $XDG_RUNTIME_DIR
PULSE_FOLDER=/run/user/$(id -u)/pulse
rm -rf ${PULSE_FOLDER}
mkdir -p ${PULSE_FOLDER}
rm -f /run/user/$(id -u)/pipewire-*
sleep 1s

function link_pipewire_socket() {
    PRIVATE_SOCKET=/run/user/$(id -u)/snap.pipewire/pipewire-0
    PUBLIC_SOCKET=/run/user/$(id -u)/pipewire-0
    while :; do
        sleep 1s
        if [ -S "$PRIVATE_SOCKET" ]; then
            ln -f "$PRIVATE_SOCKET" "$PUBLIC_SOCKET"
            return
        fi
    done
}
link_pipewire_socket &

function link_pulse_socket() {
    PRIVATE_SOCKET=/run/user/$(id -u)/snap.pipewire/pulse/native
    PUBLIC_SOCKET=/run/user/$(id -u)/pulse/native
    while :; do
        sleep 1s
        if [ -S "$PRIVATE_SOCKET" ]; then
            ln -f "$PRIVATE_SOCKET" "$PUBLIC_SOCKET"
            return
        fi
    done
}
link_pulse_socket &
