#!/bin/sh

mkdir -p $XDG_RUNTIME_DIR

rm -f $XDG_RUNTIME_DIR/../pipewire-*
rm -rf $XDG_RUNTIME_DIR/../pulse

mkdir -p $XDG_RUNTIME_DIR/../pulse

ln -f -s $XDG_RUNTIME_DIR/pipewire-0 $XDG_RUNTIME_DIR/../pipewire-0
ln -f -s $XDG_RUNTIME_DIR/pipewire-0.lock $XDG_RUNTIME_DIR/../pipewire-0.lock
ln -f -s $XDG_RUNTIME_DIR/pulse/native $XDG_RUNTIME_DIR/../pulse/native
ln -f -s $XDG_RUNTIME_DIR/pulse/pid $XDG_RUNTIME_DIR/../pulse/pid
