name: pipewire
base: core24
adopt-info: pipewire
summary: Pipewire server, plus wireplumber and pipewire-pulse
description: |
  The pipewire video/audio daemon server.

grade: stable
confinement: strict

layout:
  /usr/share/pipewire:
    bind: $SNAP/usr/share/pipewire
  /usr/share/wireplumber:
    bind: $SNAP/usr/share/wireplumber
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/alsa-card-profile:
    bind: $SNAP/usr/share/alsa-card-profile
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pipewire-0.3:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pipewire-0.3
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/wireplumber-0.5:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/wireplumber-0.5
  /etc/alsa:
    bind: $SNAP/etc/alsa
  /etc/pulse:
    bind: $SNAP/etc/pulse

environment:
  SPA_PLUGIN_DIR: $SNAP/usr/lib/x86_64-linux-gnu/spa-0.2
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/lib:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pipewire-0.3:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio

apps:
  pipewire-bin:
    command: usr/bin/pipewire
    daemon: simple
    restart-condition: always
    sockets:
      pipewire-socket:
        listen-stream: $XDG_RUNTIME_DIR/pipewire-0
        socket-mode: 0644
      pipewire-manager-socket:
        listen-stream: $XDG_RUNTIME_DIR/pipewire-0-manager
        socket-mode: 0644
    before:
      - wireplumber-bin
    passthrough:
      daemon-scope: user
    slots: &pwslots
# we have to wait until this is added to the store
#      - pipewire
      - audio-playback
      - audio-record
      - pulseaudio
    plugs: &pwplugs
      - alsa
      - bluez
      - camera
      - hardware-observe
      - media-control
      - network
      - network-bind
      - system-observe

  wireplumber-bin:
    command: usr/bin/wireplumber
    daemon: simple
    restart-condition: always
    after:
      - pipewire-bin
    passthrough:
      daemon-scope: user
    slots: *pwslots
    plugs: *pwplugs

  pipewire-pulse:
    command: usr/bin/pipewire-pulse
    daemon: simple
    restart-condition: always
    passthrough:
      daemon-scope: user
    sockets:
      pulse-socket:
        listen-stream: $XDG_RUNTIME_DIR/pulse/native
        socket-mode: 0644
    slots: *pwslots
    plugs: *pwplugs

# apps for server-wide daemon
  pipewire-server-bin:
    command: usr/bin/pipewire
    daemon: simple
    restart-condition: always
    before:
      - wireplumber-server-bin
    install-mode: disable
    slots: *pwslots
    plugs: *pwplugs

  wireplumber-server-bin:
    command: usr/bin/wireplumber
    daemon: simple
    restart-condition: always
    after:
      - pipewire-server-bin
    install-mode: disable
    slots: *pwslots
    plugs: *pwplugs

  pipewire-server-pulse:
    command: usr/bin/pipewire-pulse
    daemon: simple
    restart-condition: always
    after:
      - pipewire-server-bin
      - wireplumber-server-bin
    install-mode: disable
    slots: *pwslots
    plugs: *pwplugs

slots:
  dbus-wireplumber:
    interface: dbus
    name: org.freedesktop.ReserveDevice1
    bus: session
  dbus-pulseaudio:
    interface: dbus
    name: org.pulseaudio.Server
    bus: session

parts:
  pipewire:
    plugin: meson
    source: https://git.launchpad.net/ubuntu/+source/pipewire
    source-branch: 'applied/ubuntu/oracular'
    source-type: git
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dexamples=disabled
      - -Dman=disabled
      - -Dtests=disabled
      - -Dsystemd=enabled
      - -Dsnap=enabled
      - -Dsystemd-user-service=enabled
    override-pull: |
      craftctl default
      git_ver="$(git describe --tags --match "applied/*")"
      git_ver="${git_ver#importer/}"
      git_ver="${git_ver#applied/}"
      git_ver="${git_ver%-0-g*}"
      craftctl set version="${git_ver}"
    build-packages:
      - dpkg-dev
      - debhelper-compat
      - graphviz
      - libapparmor-dev
      - libasound2-dev
      - libavahi-client-dev
      - libbluetooth-dev
      - libcamera-dev
      - libdbus-1-dev
      - libffado-dev
      - libfreeaptx-dev
      - libglib2.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libjack-jackd2-dev
      - libcanberra-dev
      - liblc3-dev
      - libldacbt-abr-dev
      - libldacbt-enc-dev
      - liblilv-dev
      - libmysofa-dev
      - libncurses-dev
      - libopus-dev
      - libpulse-dev
      - libreadline-dev
      - libroc-dev
      - libsbc-dev
      - libsdl2-dev
      - libsnapd-glib-dev
      - libsndfile1-dev
      - libssl-dev
      - libsystemd-dev
      - libudev-dev
      - libusb-1.0-0-dev
      - libv4l-dev
      - libwebrtc-audio-processing-dev
      - libxfixes-dev
      - meson
      - modemmanager-dev
      - pkgconf
      - python3-docutils
      - systemd-dev
    stage-packages:
      - libxfixes3
      - libcanberra0t64
      - libroc0.3
      - libvorbisfile3
      - libpulse0
      - libffado2
      - liblilv-0-0
      - libavahi-client3
      - libopusenc0
      - libopus0
      - libudev1
      - libsnapd-glib-2-1
      - libbluetooth3
      - libjson-glib-1.0-0
      - libnghttp2-14
      - libpsl5t64
      - libsoup-3.0-0
      - libwebrtc-audio-processing1
      - libasound2t64
      - libgstreamer-plugins-base1.0-0
      - libmysofa1
      - libcamera0.2
      - libldacbt-enc2
      - libsbc1
      - liblc3-1
      - libldacbt-abr2
      - libfreeaptx0
      - libfdk-aac2
      - libflac12t64
      - libmp3lame0
      - libmpg123-0t64
      - libogg0
      - libsndfile1
      - libvorbisenc2
      - libvorbis0a
      - libusb-1.0-0
      - psmisc
      - bluez-alsa-utils
      - yaru-theme-sound
      - pulseaudio-utils
      - alsa-utils

    stage:
      - -usr/bin/meson
      - -usr/bin/ninja
      - -usr/lib/python3
      - -etc/pulse/client.conf.d/01-enable-autospawn.conf
      - -usr/share/doc
      - -usr/share/pkgconfig
      - -usr/share/upstart
      - -usr/share/man
      - -usr/share/session-migration
      - -usr/include
